name: TRASH
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Jakarta
      
    - name: TRASH
      run: |
        echo "$(date +%F-%T)" > TRASH.txt
        
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      with:
          git_user_signingkey: true
          git_commit_gpgsign: true
      env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: BECOME A TRASH MAN
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: Angga
          commit_user_email: angga@linuxmail.org
          commit_author: Angga <angga@linuxmail.org>
        
